version: '2.2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:4.0
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - user-web

  user-web:
    image: user-web:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url:jdbc:mysql://mysql:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - spring.datasource.username:root
      - spring.datasource.password:password
      - server.port=8080
    depends_on:
      - mysql
      - redis

  manager-web:
    image: manager-web:latest
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url:jdbc:mysql://mysql:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - spring.datasource.username:root
      - spring.datasource.password:password
      - server.port=9090
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data: {}
  redis-data: {}