#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  #jpa
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.hanslaser.blog.config.MySqlPhysicalNamingStrategyStandardImpl
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  #redis
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1


email:
  enabled: true
  host: 172.18.50.22
  port: 25
  useCredentials: true
  username: NEOA@hanslaser.com
  password: hansoa%2018
  tls: false
  smtp:
    starttls:
      enable: false








